### ISSUE TITLE
Question: Refreshing spotify auth

### ISSUE THREAD

**Issue by HorstBort** [home-assistant-libs/pychromecast#369] opened 2020-06-01 15:29 UTC
Hi,

I've been using your excellent library in my current toy project. Is there a possibility to refresh Spotify credentials? I can launch the spotify app successfully, but playback stops after the auth token is expired. If that happens, there doesn't seem to be a way to reanimate the app, apart from quitting and relaunching, which means it forgets its playback status.

So, do you now of any way to refresh the auth token for the running app?

Best,
Hauke

**Comment by balloob** [comment] 2020-06-01 16:38
Refreshing Spotify auth is out of scope for this library.

**Closed by balloob** 2020-06-01 16:38 UTC

**Comment by HorstBort** [comment] 2020-06-01 22:38
Hi, I realize that I may have worded the question a bit unclearly. Getting a new auth token is not the issue, I was just wondering if there is an api endpoint for getting the new token to the chromecast spotify app without killing and relaunching it.

I tried

    sp = SpotifyController(access_token, expires)
    cast.register_handler(sp)
    sp.launch_app()

Wait for e.g. 30 minuten and then:

    sp.send_message({'type': 'setCredentials',
                                    'credentials': new_access_token,
                                    'expiresIn': new_expires})

Unfortunately, that does not do the trick, playback stops after ```expires```, so typically after ```3600 s```. Is there by any chance a ```setNewCredentials``` message? Or maybe documentation of the Spotify Chromecast App? I know, it's a long shot...

Anyway, I just thought I'd clarify my question.

I really appreciate your quick response!

**Comment by MagicMicky** [comment] 2020-08-25 17:25
@HorstBort have you managed to find anything? I'm trying to figure out this topic myself!

**Comment by emontnemery** [comment] 2020-08-25 17:53
@fondberg could renewal of the token be added to the spotify example?

**Comment by MagicMicky** [comment] 2020-08-25 20:54
@emontnemery as an FYI, from my understanding the issue is the following:
After launching the Spotify app on chromecast, pychromecast uses the `access_token` to [set the credentials](https://github.com/home-assistant-libs/pychromecast/blob/master/pychromecast/controllers/spotify.py#L71-L77) on the app. Unfortunately those credentials have an expiry time (usually 1h)

Once the `access_token` is expired, the playback stop. Much to our luck, when generating the access_token, we're also given a `refresh_token`, which in my understanding should be used to regenerate a new `access_token` and forward it to the app. Unfortunately I didn't find documentation or implementation regarding this part.

I'm still confused as to where the knowledge of the `setCredentials` linked above come from as well, and I suppose it's via reverse engineering. I've been trying to use wireshark to see the flow executed by a desktop/mobile app, but without luck. I added information in the spotcast issue:  https://github.com/fondberg/spotcast/issues/13#issuecomment-680189631

I've also opened a new ticket here asking for some more details of implementation: https://github.com/home-assistant-libs/pychromecast/issues/407

FYI I'm not looking for a solution, and I might help implementing it, if I manage to figure out the workflow of other apps, which is where I had not much luck until now.

**Comment by HorstBort** [comment] 2020-08-26 14:30
> @HorstBort have you managed to find anything? I'm trying to figure out this topic myself!

@MagicMicky Well, kind of. I settled for a workaround: In my app, I look if playback time actually advances. If not, I get a new `access_token`, quit the app on the chromecast and start it again :-/. Then, I transfer playback to the chromecast again, and it will thankfully resume roughly where it stopped due to the expired token.

**Comment by fondberg** [comment] 2020-08-26 15:41
> @fondberg can you help shed some light on this, is it expected that playback stops after 1 hour?

I've outlined this topic in the first open issue in spotcast where I think this discussion should proceed as it is not pychromecasts responsibility.

**Comment by emontnemery** [comment] 2020-08-26 15:57
Spotcast issue: fondberg/spotcast#13
